ALTER TABLE branch ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE grain_type ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE truck ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE scale ADD COLUMN version BIGINT NOT NULL DEFAULT 0;